/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTag: typeof import('element-plus/es')['ElTag']
    MoDrawer: typeof import('./src/components/MoDrawer.vue')['default']
    MoSlogen: typeof import('./src/components/MoSlogen.vue')['default']
    MoTag: typeof import('./src/components/MoTag.vue')['default']
    MoTextarea: typeof import('./src/components/MoTextarea.vue')['default']
  }
}
